### ISSUE TITLE
Could not access pretrained ckpt

### ISSUE THREAD

**Issue by xuanyech** [google-research/3d-moments#9]

**Comment by qianqianwang68** [comment]
Hi, I no longer have access to this repo, but here is the updated pretrained checkpoint link:

https://drive.google.com/file/d/1qBFngVXcSUiydXC9MUwU_taFQs3xjykY/view?usp=sharing

**Comment by xuanyech** [comment]
> Hi, I no longer have access to this repo, but here is the updated pretrained checkpoint:
> 
> https://drive.google.com/file/d/1qBFngVXcSUiydXC9MUwU_taFQs3xjykY/view?usp=sharing

Thanks for your kind help!
